spring:
  application:
    name: User Service
  datasource:
    url: jdbc:postgresql://localhost:5432/driving
    password: root
    username: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
server:
  port: 0

jwt:
  secretKey:
    dev:
      key: BjcLgSkRs8AYJ06eJgjBqPxosBbNS0I42jNj/JqkUn0=
      expiration_access_token: 300000
      expiration_refresh_token: 1296000000